import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useMemo } from "react";

export default function Home({ data }) {
  const selected = useMemo(() => {
    if (!data || data.length < 1) {
      return;
    }

    const randomNumber = Math.floor(Math.random() * data.length);

    return data[randomNumber];
  }, [data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {selected && (
          <blockquote>
            <p className="quote">&ldquo;{selected.quote}&rdquo;</p>
            <p>- {selected.source}</p>
          </blockquote>
        )}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  let data = null;

  try {
    const res = await fetch(
      "https://api.github.com/gists/68cf4acca22d7dca00eadd4e54b7f53c",
      {
        headers: {
          Authorization: `token ${process.env.PAT}`,
        },
      }
    );

    data = await res.json();

    console.log(data);

    data = JSON.parse(data.files["sopranos-quotes.json"].content);
  } catch (error) {
    console.error(error)
  }

  return { props: { data } };
}
